title: Linux command dictionary
description: A dictionary for linux command
author: Jingjing Shi
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/codeasashu
about: Freelance developer

baseurl: "https://cmddictblog.github.io"
url: "https://cmddictblog.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
